# pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: my-container
      image: nginx  # Replace with your desired container image
      ports:
        - containerPort: 80
      volumeMounts:
        - name: my-pvc-volume
          mountPath: /usr/share/nginx/html  # Replace with the path to mount the PVC inside the container
  volumes:
    - name: my-pvc-volume
      persistentVolumeClaim:
        claimName: my-pvc  # Use the PVC name you created earlier
