apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: k8s-go
  name: k8s-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: k8s-go
    spec:
      containers:
      - image: quay.io/oviner/k8s-go:0.1.0
        name: k8s-go
        resources: {}
status: {}
