# roles/web_server/tasks/main.yml
---
- name: Install Apache on Fedora
  dnf:
    name: httpd
    state: present

- name: Start and enable Apache service on Fedora
  service:
    name: httpd
    state: started
    enabled: yes

- name: Copy index.html to web root on Fedora
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache
